/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./index.html"],
  theme: {
    extend: {
      colors: {
        "app-primary": "var(--app-primary)",
        "app-secondary": "var(--app-secondary)",
        black: "var(--black)",
        "neutralgray-2d2d2d": "var(--neutralgray-2d2d2d)",
        "neutralgray-444444": "var(--neutralgray-444444)",
        "neutralgray-505050": "var(--neutralgray-505050)",
        "neutralgray-717171": "var(--neutralgray-717171)",
        "neutralgray-9e9e9e": "var(--neutralgray-9e9e9e)",
        "neutralgray-b4b4b4": "var(--neutralgray-b4b4b4)",
        "neutralgray-cbcbcb": "var(--neutralgray-cbcbcb)",
        "neutralgray-ededed": "var(--neutralgray-ededed)",
        "neutralgray-f6f6f6": "var(--neutralgray-f6f6f6)",
        "neutralgray-f9f9f9": "var(--neutralgray-f9f9f9)",
        "primaryprimary-100": "var(--primaryprimary-100)",
        "primaryprimary-200": "var(--primaryprimary-200)",
        "primaryprimary-25": "var(--primaryprimary-25)",
        "primaryprimary-300": "var(--primaryprimary-300)",
        "primaryprimary-400": "var(--primaryprimary-400)",
        "primaryprimary-50": "var(--primaryprimary-50)",
        "primaryprimary-500": "var(--primaryprimary-500)",
        "primaryprimary-600": "var(--primaryprimary-600)",
        "primaryprimary-700": "var(--primaryprimary-700)",
        "primaryprimary-75": "var(--primaryprimary-75)",
        "primaryprimary-900": "var(--primaryprimary-900)",
        "primarysecondarysecondary-100": "var(--primarysecondarysecondary-100)",
        "primarysecondarysecondary-200": "var(--primarysecondarysecondary-200)",
        "primarysecondarysecondary-300": "var(--primarysecondarysecondary-300)",
        "primarysecondarysecondary-400": "var(--primarysecondarysecondary-400)",
        "primarysecondarysecondary-500": "var(--primarysecondarysecondary-500)",
        "primarysecondarysecondary-600": "var(--primarysecondarysecondary-600)",
        stateerror: "var(--stateerror)",
        "stateerror-light": "var(--stateerror-light)",
        statesuccess: "var(--statesuccess)",
        "statesuccess-light": "var(--statesuccess-light)",
        white: "var(--white)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "logo-slog": "var(--logo-slog-font-family)",
        "logo-title": "var(--logo-title-font-family)",
        "mobile-body-lg": "var(--mobile-body-lg-font-family)",
        "mobile-body-md": "var(--mobile-body-md-font-family)",
        "mobile-body-sm": "var(--mobile-body-sm-font-family)",
        "mobile-button-lg": "var(--mobile-button-lg-font-family)",
        "mobile-button-sm": "var(--mobile-button-sm-font-family)",
        "mobile-caption": "var(--mobile-caption-font-family)",
        "mobile-h1": "var(--mobile-h1-font-family)",
        "mobile-h2": "var(--mobile-h2-font-family)",
        "mobile-h3": "var(--mobile-h3-font-family)",
        "mobile-h4": "var(--mobile-h4-font-family)",
        "mobile-overline": "var(--mobile-overline-font-family)",
        "web-body-lg": "var(--web-body-lg-font-family)",
        "web-body-md": "var(--web-body-md-font-family)",
        "web-body-sm": "var(--web-body-sm-font-family)",
        "web-body-xl": "var(--web-body-xl-font-family)",
        "web-body-xs": "var(--web-body-xs-font-family)",
        "web-button-lg": "var(--web-button-lg-font-family)",
        "web-button-sm": "var(--web-button-sm-font-family)",
        "web-caption-lg": "var(--web-caption-lg-font-family)",
        "web-caption-md": "var(--web-caption-md-font-family)",
        "web-caption-sm": "var(--web-caption-sm-font-family)",
        "web-display1": "var(--web-display1-font-family)",
        "web-display2": "var(--web-display2-font-family)",
        "web-h1": "var(--web-h1-font-family)",
        "web-h2": "var(--web-h2-font-family)",
        "web-h3": "var(--web-h3-font-family)",
        "web-h4": "var(--web-h4-font-family)",
        "web-h5": "var(--web-h5-font-family)",
        "web-h6": "var(--web-h6-font-family)",
        "web-overline-lg": "var(--web-overline-lg-font-family)",
        "web-overline-sm": "var(--web-overline-sm-font-family)",
        "web-underline-primary": "var(--web-underline-primary-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: {
        "shadow-1": "var(--shadow-1)",
        "shadow-2": "var(--shadow-2)",
        "shadow-3": "var(--shadow-3)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        shine: {
          "0%": { backgroundPosition: "200% 0" },
          "25%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        gradientFlow: {
          "0%": { "background-position": "0% 50%" },
          "50%": { "background-position": "100% 50%" },
          "100%": { "background-position": "0% 50%" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        shine: "shine 3s ease-out infinite",
        "gradient-flow":
          "gradientFlow 10s ease 0s infinite normal none running",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  future: {
    // Enable v4 features
    hoverOnlyWhenSupported: true,
    respectDefaultRingColorOpacity: true,
    disableColorOpacityUtilitiesByDefault: true,
    colorDestructuring: true,
  },
  darkMode: ["class"],
};
